#!/usr/bin/env bash
# =============================================================================
# test-doc-generation.sh
# End-to-end test for the Legal Express document generation pipeline.
#
# Usage:
#   chmod +x scripts/test-doc-generation.sh
#   ./scripts/test-doc-generation.sh
#
# Requires: curl, jq
# App must be running: npm run dev (in apps/backend)
# =============================================================================
set -euo pipefail

BASE_URL="${BASE_URL:-http://localhost:3000}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@legalexpress.com}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-password123}"
MAX_WAIT=30   # seconds to wait for generation

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

pass() { echo -e "${GREEN}[PASS] $1${NC}"; }
fail() { echo -e "${RED}[FAIL] $1${NC}"; exit 1; }
info() { echo -e "${BLUE}[INFO] $1${NC}"; }
warn() { echo -e "${YELLOW}[WARN] $1${NC}"; }

echo ""
echo -e "${BLUE}══════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Legal Express — Document Generation Test    ${NC}"
echo -e "${BLUE}══════════════════════════════════════════════${NC}"
echo ""

# ── 0. Health check ──────────────────────────────────────────────────────────
info "Checking backend is reachable at $BASE_URL ..."
if ! curl -sf "$BASE_URL/health" > /dev/null 2>&1; then
    fail "Backend not reachable. Start it with: cd apps/backend && npm run dev"
fi
pass "Backend is up"

# ── 1. Authenticate ──────────────────────────────────────────────────────────
info "Logging in as $ADMIN_EMAIL ..."
AUTH_RESPONSE=$(curl -sf -X POST "$BASE_URL/api/auth/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\"}")

TOKEN=$(echo "$AUTH_RESPONSE" | jq -r '.token // empty')
if [ -z "$TOKEN" ]; then
    fail "Login failed. Response: $AUTH_RESPONSE"
fi
pass "Authenticated — token obtained"

# ── 2. Generate document (PDF) ────────────────────────────────────────────────
USER_ID=$(cat /proc/sys/kernel/random/uuid 2>/dev/null || uuidgen | tr '[:upper:]' '[:lower:]')
info "Requesting PDF document for user $USER_ID ..."

GENERATE_RESPONSE=$(curl -sf -X POST "$BASE_URL/api/generate-doc" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $TOKEN" \
    -d "{
        \"formId\": \"legal-doc-request\",
        \"userId\": \"$USER_ID\",
        \"outputFormat\": \"pdf\",
        \"formData\": {
            \"fullName\": \"Diego Pardo\",
            \"email\": \"engineer.pardo@gmail.com\",
            \"phone\": \"+1 (555) 000-0000\",
            \"documentType\": \"INVOICE\",
            \"description\": \"Test invoice generated by automated test script.\",
            \"dueDate\": \"2026-04-01\",
            \"estimatedAmount\": 5000,
            \"urgent\": false
        }
    }")

DOCUMENT_ID=$(echo "$GENERATE_RESPONSE" | jq -r '.documentId // empty')
JOB_ID=$(echo "$GENERATE_RESPONSE" | jq -r '.jobId // empty')

if [ -z "$DOCUMENT_ID" ]; then
    fail "Document generation failed. Response: $GENERATE_RESPONSE"
fi
pass "Document queued — documentId: $DOCUMENT_ID | jobId: $JOB_ID"

# ── 3. Poll status until COMPLETED ──────────────────────────────────────────
info "Waiting for PDF generation (max ${MAX_WAIT}s) ..."
ELAPSED=0
FILE_URL=""
while [ $ELAPSED -lt $MAX_WAIT ]; do
    STATUS_RESPONSE=$(curl -sf "$BASE_URL/api/documents/$DOCUMENT_ID/status")
    STATUS=$(echo "$STATUS_RESPONSE" | jq -r '.status // "unknown"')
    FILE_URL=$(echo "$STATUS_RESPONSE" | jq -r '.fileUrl // empty')

    echo -e "   [$ELAPSED s] status: ${YELLOW}$STATUS${NC}"

    if [ "$STATUS" = "completed" ]; then
        break
    elif [ "$STATUS" = "failed" ]; then
        fail "Document generation failed on the server."
    fi

    sleep 2
    ELAPSED=$((ELAPSED + 2))
done

if [ "$STATUS" != "completed" ]; then
    fail "Timed out waiting for document (last status: $STATUS)"
fi
pass "PDF generated — fileUrl: $FILE_URL"

# ── 4. Download and verify the PDF ──────────────────────────────────────────
if [ -n "$FILE_URL" ]; then
    info "Downloading PDF ..."
    DOWNLOAD_PATH="/tmp/legal-express-test-$DOCUMENT_ID.pdf"
    curl -sf "$BASE_URL$FILE_URL" -o "$DOWNLOAD_PATH"

    FILE_SIZE=$(wc -c < "$DOWNLOAD_PATH")
    HEADER=$(head -c 4 "$DOWNLOAD_PATH" | cat -v 2>/dev/null || xxd "$DOWNLOAD_PATH" | head -1)

    if [ "$FILE_SIZE" -lt 1000 ]; then
        fail "PDF seems too small ($FILE_SIZE bytes) — something may have gone wrong."
    fi
    pass "PDF downloaded: $DOWNLOAD_PATH ($FILE_SIZE bytes)"
    echo -e "   Header bytes: $HEADER"
fi

# ── 5. List documents via authenticated endpoint ─────────────────────────────
info "Listing documents ..."
LIST_RESPONSE=$(curl -sf "$BASE_URL/api/documents" \
    -H "Authorization: Bearer $TOKEN")

DOC_COUNT=$(echo "$LIST_RESPONSE" | jq '.documents | length' 2>/dev/null || echo "?")
pass "Documents listed — count: $DOC_COUNT"

# ── 6. DOCX merge test (local, no HTTP) ──────────────────────────────────────
info "Testing DOCX template merge ..."
cd "$(dirname "$0")/.."

if npx tsx scripts/test-docx-merge.ts > /tmp/docx-test.log 2>&1; then
    DOCX_PATH=$(tail -1 /tmp/docx-test.log)
    pass "DOCX merged: $DOCX_PATH"
else
    warn "DOCX merge test failed (see /tmp/docx-test.log)"
    cat /tmp/docx-test.log
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  All checks passed!                          ${NC}"
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo ""
echo "  Document ID : $DOCUMENT_ID"
echo "  PDF path    : ${DOWNLOAD_PATH:-$FILE_URL}"
echo ""
